# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.Controllers.UserController import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLogin = QtWidgets.QTextBrowser(self.centralwidget)
        self.titleLogin.setGeometry(QtCore.QRect(210, 20, 361, 61))
        self.titleLogin.setObjectName("titleLogin")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(330, 170, 131, 41))
        self.loginButton.setStyleSheet("background-color: rgb(59, 146, 23);")
        self.loginButton.setObjectName("loginButton")
        self.addLogin = QtWidgets.QTextEdit(self.centralwidget)
        self.addLogin.setGeometry(QtCore.QRect(100, 110, 261, 41))
        self.addLogin.setObjectName("addLogin")
        self.addPassword = QtWidgets.QTextEdit(self.centralwidget)
        self.addPassword.setGeometry(QtCore.QRect(430, 110, 261, 41))
        self.addPassword.setObjectName("addPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Информационная система КАФЕ"))
        self.titleLogin.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Приветствуем Вас в информационной системе КАФЕ</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Пожалуйста введите свой логин и пароль</p></body></html>"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.addLogin.setPlaceholderText(_translate("MainWindow", "Введите свой логин"))
        self.addPassword.setPlaceholderText(_translate("MainWindow", "Введите свой пароль"))

    def test_button(self):
         log = self.addLogin.toPlainText()
         passwd = self.addPassword.toPlainText()
         user = UserController()
         result = user.log_in(log,passwd)
         print(result)
    def pressButton(self):
        self.loginButton.clicked.connect(self.test_button)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pressButton()
    sys.exit(app.exec_())
